---
# k3s server config file.

write-kubeconfig-mode: "0644"
cluster-init: true
log: "/var/lib/rancher/k3s/k3s.log"
debug: true
etcd-expose-metrics: true
container-runtime-endpoint: "/run/containerd-user/containerd.sock"
